language: perl
perl:     5.20
sudo:     false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8

env:
  matrix:
    - VER_NGINX=1.8.0

install:
  - mkdir ./vendor && cd ./vendor

  - wget "http://nginx.org/download/nginx-${VER_NGINX}.tar.gz" -O nginx.tar.gz && tar -xf nginx.tar.gz

  - cd "${TRAVIS_BUILD_DIR}/vendor/nginx-${VER_NGINX}"
  - ./configure --add-module="${TRAVIS_BUILD_DIR}"
  - make
  - export PATH="$PATH:${TRAVIS_BUILD_DIR}/vendor/nginx-${VER_NGINX}/objs"

  - cpanm -v --notest Test::Nginx

script: cd ${TRAVIS_BUILD_DIR} && prove
